### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by AjroudiRida** [AbuTalha3/Rock-Climbing-Competition-Fixture#2]
**Good Work**

Linters well set up and passing ✔️
The mobile view looks great ✔️
Hamburger menu works as expected ✔️
Team section generated dynamically from javascript ✔️
Website looks similar to Behnace Design ✔️
Great walkthrough video

**Required**

- The readme file is messing the credit section

**Comment by AbuTalha3** [comment]
closed
